openapi: 3.0.1
info:
  title: Secure Auth System API
  version: 1.0.0
  description: API for authentication system (registration, login, device sessions, token refresh)
servers:
  - url: http://localhost:3000/api
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  timestamp:
                    type: string
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register'
      responses:
        '201':
          description: Created
  /auth/login:
    post:
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
  /auth/logout:
    post:
      summary: Logout current session
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Logged out
  /auth/refresh:
    post:
      summary: Refresh tokens
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Refresh'
      responses:
        '200':
          description: New tokens
  /users/me:
    get:
      summary: Get profile of authenticated user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSafe'
  /sessions:
    get:
      summary: List active sessions for user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Register:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        firstName:
          type: string
        lastName:
          type: string
      required: [email, password, firstName, lastName]
    Login:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        deviceInfo:
          type: object
    Refresh:
      type: object
      properties:
        refreshToken:
          type: string
        deviceId:
          type: string
      required: [refreshToken, deviceId]
    LoginResponse:
      type: object
      properties:
        message:
          type: string
        user:
          $ref: '#/components/schemas/UserSafe'
        tokens:
          type: object
          properties:
            accessToken:
              type: string
            refreshToken:
              type: string
        deviceId:
          type: string
    UserSafe:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
